---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # HACK: https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir
      - name: Fix permissions
        run: chmod 0755 ansible/


      - name: Set up
        run: ./scripts/setup.sh
      - name: Pretend executable is vault password
        run: chmod -x ansible/scripts/vault.sh
      - name: Lint
        run: ./scripts/lint.sh